# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: fastimage_resize 3.0.0 ruby lib
# stub: ext/fastimage_resize/extconf.rb

Gem::Specification.new do |s|
  s.name = "fastimage_resize".freeze
  s.version = "3.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Stephen Sykes".freeze, "Yusuke Sakurai".freeze]
  s.date = "2020-03-31"
  s.description = "FastImage Resize is an extremely light solution for resizing images in ruby by using libgd.".freeze
  s.email = "do-not-send@loilo.tv".freeze
  s.extensions = ["ext/fastimage_resize/extconf.rb".freeze]
  s.extra_rdoc_files = [
    "README",
    "README.textile"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "MIT_LICENCE",
    "Makefile",
    "README",
    "README.textile",
    "Rakefile",
    "VERSION.yml",
    "ext/fastimage_resize/extconf.rb",
    "ext/fastimage_resize/fastimage_resize.c",
    "fastimage_resize.gemspec",
    "lib/fastimage_resize.rb",
    "mkmf.log",
    "test/fixtures/faulty.jpg",
    "test/fixtures/test with space.jpg",
    "test/fixtures/test.bmp",
    "test/fixtures/test.gif",
    "test/fixtures/test.ico",
    "test/fixtures/test.jpg",
    "test/fixtures/test.png",
    "test/test.rb"
  ]
  s.homepage = "http://github.com/loilo-inc/fastimage_resize".freeze
  s.licenses = ["MIT".freeze]
  s.requirements = ["libgd, see www.libgd.org".freeze]
  s.rubygems_version = "3.1.2".freeze
  s.summary = "FastImage Resize - Image resizing fast and simple".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<fastimage>.freeze, ["~> 2.1"])
    s.add_runtime_dependency(%q<jeweler>.freeze, [">= 0"])
  else
    s.add_dependency(%q<fastimage>.freeze, ["~> 2.1"])
    s.add_dependency(%q<jeweler>.freeze, [">= 0"])
  end
end

